version: "3"

services:
    front:
        container_name: front
        image: hippotech-front-with-seeker:latest
        environment: 
            APPROVAL_URL: "http://approval:4002"
            BLOG_URL: "http://blog:4003"
        ports:
            - 4001:4001

    approval:
        container_name: approval
        image: hippotech-approval-with-seeker:latest
        ports:
            - 4002:4002

    demo:
        container_name: demo
        image: demo:latest
        ports:
            - 4444:4444

    blog:
        container_name: blog
        image: hippotech-blog-with-seeker:latest
        ports:
          - 4003:4003
        environment: 
            MONGO_URL: "mongodb://mongo:27017"
        depends_on: 
          - mongo
          
    mongo:
        container_name: 'mongo'
        image: mongo:4.4.3-bionic