FROM hippotech-approval:latest
RUN echo agent bump 4
RUN sh -c "$(curl -k -X GET -fsSL --header 'Accept: application/x-sh' 'http://seeker-server:8080/rest/api/latest/installers/agents/scripts/JAVA?osFamily=LINUX&downloadWith=curl&projectKey=APPROVAL&webServer=OTHER&flavor=DEFAULT&agentName=Approval&accessToken=')"
ENV JAVA_OPTS="-javaagent:/seeker/seeker-agent.jar"